@extends('errors.layout')
@section('title', 'Page not found')
@section('code', '404')
@section('heading', 'We could not find that page')
@section('message', 'The link may be old or mistyped. Go to the home page and start again.')
