<?php

/**
 * The icon each badge shows (a Phosphor Icons "fill" icon, MIT licence, see public/icons/LICENSE-phosphor.txt),
 * chosen to say what the badge means. The names match the symbols in public/icons/badges.svg. The emoji in
 * config/badges.php are kept only as a plain-text fallback and for the mobile API.
 */
return [

    'fallback' => 'medal',

    'icons' => [
        'first_reading_star' => 'star',
        'read_sprout_reader' => 'plant',
        'readings_10' => 'book-open',
        'readings_25' => 'books',
        'read_bookworm' => 'book-open-text',
        'read_page_turner' => 'file-text',
        'read_century_reader' => 'certificate',
        'read_story_explorer' => 'globe-hemisphere-west',
        'read_reading_champion' => 'trophy',
        'read_library_legend' => 'bank',
        'streak_3' => 'fire-simple',
        'streak_5_day_streak' => 'flame',
        'streak_7' => 'fire',
        'streak_10_day_streak' => 'rainbow',
        'streak_14_day_streak' => 'lightning',
        'streak_21_day_streak' => 'butterfly',
        'streak_30_day_streak' => 'moon-stars',
        'streak_50_day_streak' => 'shield-star',
        'streak_75_day_streak' => 'horse',
        'streak_100_day_streak' => 'crown',
        'acc_on_target' => 'target',
        'acc_clear_voice' => 'speaker-high',
        'acc_sharp_eyes' => 'eye',
        'acc_word_whiz' => 'brain',
        'acc_perfect_reading' => 'diamond',
        'acc_triple_perfect' => 'medal-military',
        'acc_steady_hands' => 'hand-palm',
        'acc_precision_pro' => 'crosshair',
        'acc_practice_pays_off' => 'flower',
        'acc_flawless_five' => 'sparkle',
        'speed_steady_pace' => 'person-simple-walk',
        'speed_getting_faster' => 'rabbit',
        'speed_quick_reader' => 'bicycle',
        'speed_speedy_reader' => 'person-simple-run',
        'speed_swift_reader' => 'bird',
        'speed_rocket_reader' => 'rocket',
        'speed_race_car_reader' => 'car-profile',
        'speed_cheetah_reader' => 'paw-print',
        'speed_jet_reader' => 'airplane',
        'speed_comet_reader' => 'shooting-star',
        'leveled_up' => 'trend-up',
        'level_developing_reader' => 'leaf',
        'level_proficient_reader' => 'seal-check',
        'level_steady_climber' => 'sneaker',
        'level_summit_seeker' => 'mountains',
        'level_comeback_kid' => 'arrows-clockwise',
        'level_holding_strong' => 'shield-check',
        'level_graduate' => 'graduation-cap',
        'level_skill_climber' => 'stairs',
        'level_all_skills_star' => 'star-four',
        'goal_first_goal' => 'flag-banner',
        'goal_two_weeks_strong' => 'calendar-check',
        'goal_goal_getter' => 'cloud-sun',
        'goal_finish_line' => 'flag-checkered',
        'goal_early_finisher' => 'timer',
        'goal_overachiever' => 'plus-circle',
        'goal_perfect_week' => 'check-circle',
        'goal_weekend_reader' => 'sun',
        'goal_monthly_milestone' => 'confetti',
        'goal_goal_master' => 'crown-simple',
        'pts_first_100_points' => 'coin',
        'pts_200_points' => 'coins',
        'pts_500_points' => 'money',
        'pts_750_points' => 'piggy-bank',
        'pts_1_000_points' => 'gift',
        'pts_1_500_points' => 'shopping-bag',
        'pts_2_000_points' => 'balloon',
        'pts_3_000_points' => 'cake',
        'pts_5_000_points' => 'castle-turret',
        'pts_10_000_points' => 'planet',
        'shelf_book_collector' => 'bookmark-simple',
        'shelf_five_on_the_shelf' => 'archive',
        'shelf_ten_on_the_shelf' => 'bookmarks',
        'shelf_re_read_rookie' => 'book',
        'shelf_re_read_hero' => 'repeat',
        'shelf_practice_champion' => 'barbell',
        'shelf_personal_best' => 'medal',
        'shelf_favorite_story' => 'heart',
        'shelf_cover_to_cover' => 'notebook',
        'shelf_shelf_master' => 'folders',
        'game_word_builder_rookie' => 'text-aa',
        'game_word_builder_pro' => 'cube',
        'game_master_builder' => 'hammer',
        'game_letter_match_rookie' => 'cards',
        'game_memory_master' => 'puzzle-piece',
        'game_game_on' => 'game-controller',
        'game_game_champion' => 'joystick',
        'game_lucky_match' => 'dice-five',
        'game_alphabet_ace' => 'text-t',
        'game_practice_party' => 'smiley',
        'special_reading_check_done' => 'map-trifold',
        'special_early_bird' => 'sun-horizon',
        'special_night_owl' => 'moon',
        'special_story_detective' => 'magnifying-glass',
        'special_super_detective' => 'detective',
        'special_extra_practice_explorer' => 'compass',
        'special_teamwork' => 'handshake',
        'special_taras_friend' => 'smiley-wink',
        'special_welcome_back' => 'hand-waving',
        'special_super_reader' => 'crown-cross',
    ],

];
