<?php

/**
 * Badge definitions: 100 of them, ten in each of ten categories. Fixed content
 * (not user-editable), so a config array rather than a table; only
 * `learner_badges`, which records which a learner has earned, is a table.
 * Order here is the display order.
 *
 * `rule` says how a badge is earned, worked out from real reading history by
 * App\Services\BadgeService (see its rule methods for what each `type` checks).
 * A badge with `rule => null` cannot be earned (none today). The ten Games badges are
 * earned from `game_plays`, a row Practice Games write when a session ends (the games
 * run in the browser and stay free play: no points, streak or level).
 */
return [
    'categories' => [
        'read' => 'Reading',
        'streak' => 'Streaks',
        'acc' => 'Accuracy',
        'speed' => 'Speed',
        'level' => 'Levels',
        'goal' => 'Goals',
        'pts' => 'Points',
        'shelf' => 'Bookshelf',
        'game' => 'Games',
        'special' => 'Special',
    ],

    'badges' => [
        'first_reading_star' => [
            'category' => 'read',
            'name' => 'First Reading Star',
            'description' => 'Complete your very first reading with TaraBasa.',
            'emoji' => '⭐',
            'rule' => ['type' => 'first_reading'],
        ],
        'read_sprout_reader' => [
            'category' => 'read',
            'name' => 'Sprout Reader',
            'description' => 'Finish 5 real reading activities.',
            'emoji' => '🌱',
            'rule' => ['type' => 'readings', 'target' => 5],
        ],
        'readings_10' => [
            'category' => 'read',
            'name' => '10 Readings',
            'description' => 'Finish 10 real reading activities.',
            'emoji' => '📖',
            'rule' => ['type' => 'readings', 'target' => 10],
        ],
        'readings_25' => [
            'category' => 'read',
            'name' => '25 Readings',
            'description' => 'Finish 25 real reading activities.',
            'emoji' => '📚',
            'rule' => ['type' => 'readings', 'target' => 25],
        ],
        'read_bookworm' => [
            'category' => 'read',
            'name' => 'Bookworm',
            'description' => 'Finish 50 real reading activities.',
            'emoji' => '🐛',
            'rule' => ['type' => 'readings', 'target' => 50],
        ],
        'read_page_turner' => [
            'category' => 'read',
            'name' => 'Page Turner',
            'description' => 'Finish 75 real reading activities.',
            'emoji' => '📃',
            'rule' => ['type' => 'readings', 'target' => 75],
        ],
        'read_century_reader' => [
            'category' => 'read',
            'name' => 'Century Reader',
            'description' => 'Finish 100 real reading activities.',
            'emoji' => '💯',
            'rule' => ['type' => 'readings', 'target' => 100],
        ],
        'read_story_explorer' => [
            'category' => 'read',
            'name' => 'Story Explorer',
            'description' => 'Finish 150 real reading activities.',
            'emoji' => '🌍',
            'rule' => ['type' => 'readings', 'target' => 150],
        ],
        'read_reading_champion' => [
            'category' => 'read',
            'name' => 'Reading Champion',
            'description' => 'Finish 200 real reading activities.',
            'emoji' => '🏆',
            'rule' => ['type' => 'readings', 'target' => 200],
        ],
        'read_library_legend' => [
            'category' => 'read',
            'name' => 'Library Legend',
            'description' => 'Finish 300 real reading activities.',
            'emoji' => '🏛️',
            'rule' => ['type' => 'readings', 'target' => 300],
        ],
        'streak_3' => [
            'category' => 'streak',
            'name' => '3-Day Streak',
            'description' => 'Read on 3 days in a row.',
            'emoji' => '🔥',
            'rule' => ['type' => 'day_streak', 'target' => 3],
        ],
        'streak_5_day_streak' => [
            'category' => 'streak',
            'name' => '5-Day Streak',
            'description' => 'Read on 5 days in a row.',
            'emoji' => '🕯️',
            'rule' => ['type' => 'day_streak', 'target' => 5],
        ],
        'streak_7' => [
            'category' => 'streak',
            'name' => '7-Day Streak',
            'description' => 'Read on 7 days in a row.',
            'emoji' => '🌈',
            'rule' => ['type' => 'day_streak', 'target' => 7],
        ],
        'streak_10_day_streak' => [
            'category' => 'streak',
            'name' => '10-Day Streak',
            'description' => 'Read on 10 days in a row.',
            'emoji' => '🎇',
            'rule' => ['type' => 'day_streak', 'target' => 10],
        ],
        'streak_14_day_streak' => [
            'category' => 'streak',
            'name' => '14-Day Streak',
            'description' => 'Read on 14 days in a row.',
            'emoji' => '🌋',
            'rule' => ['type' => 'day_streak', 'target' => 14],
        ],
        'streak_21_day_streak' => [
            'category' => 'streak',
            'name' => '21-Day Streak',
            'description' => 'Read on 21 days in a row. That is a real habit!',
            'emoji' => '🦋',
            'rule' => ['type' => 'day_streak', 'target' => 21],
        ],
        'streak_30_day_streak' => [
            'category' => 'streak',
            'name' => '30-Day Streak',
            'description' => 'Read on 30 days in a row.',
            'emoji' => '🌙',
            'rule' => ['type' => 'day_streak', 'target' => 30],
        ],
        'streak_50_day_streak' => [
            'category' => 'streak',
            'name' => '50-Day Streak',
            'description' => 'Read on 50 days in a row.',
            'emoji' => '🐉',
            'rule' => ['type' => 'day_streak', 'target' => 50],
        ],
        'streak_75_day_streak' => [
            'category' => 'streak',
            'name' => '75-Day Streak',
            'description' => 'Read on 75 days in a row.',
            'emoji' => '🦄',
            'rule' => ['type' => 'day_streak', 'target' => 75],
        ],
        'streak_100_day_streak' => [
            'category' => 'streak',
            'name' => '100-Day Streak',
            'description' => 'Read on 100 days in a row. Legendary!',
            'emoji' => '👑',
            'rule' => ['type' => 'day_streak', 'target' => 100],
        ],
        'acc_on_target' => [
            'category' => 'acc',
            'name' => 'On Target',
            'description' => 'Score 70% or higher on a reading.',
            'emoji' => '🎯',
            'rule' => ['type' => 'accuracy', 'min' => 70],
        ],
        'acc_clear_voice' => [
            'category' => 'acc',
            'name' => 'Clear Voice',
            'description' => 'Score 80% or higher on a reading.',
            'emoji' => '🔊',
            'rule' => ['type' => 'accuracy', 'min' => 80],
        ],
        'acc_sharp_eyes' => [
            'category' => 'acc',
            'name' => 'Sharp Eyes',
            'description' => 'Score 90% or higher on a reading.',
            'emoji' => '👀',
            'rule' => ['type' => 'accuracy', 'min' => 90],
        ],
        'acc_word_whiz' => [
            'category' => 'acc',
            'name' => 'Word Whiz',
            'description' => 'Score 95% or higher on a reading.',
            'emoji' => '🧠',
            'rule' => ['type' => 'accuracy', 'min' => 95],
        ],
        'acc_perfect_reading' => [
            'category' => 'acc',
            'name' => 'Perfect Reading',
            'description' => 'Score 100% on a reading.',
            'emoji' => '💎',
            'rule' => ['type' => 'accuracy', 'min' => 100],
        ],
        'acc_triple_perfect' => [
            'category' => 'acc',
            'name' => 'Triple Perfect',
            'description' => 'Get 3 perfect readings.',
            'emoji' => '🎖️',
            'rule' => ['type' => 'accuracy', 'min' => 100, 'count' => 3],
        ],
        'acc_steady_hands' => [
            'category' => 'acc',
            'name' => 'Steady Hands',
            'description' => 'Score 80% or higher on 5 readings in a row.',
            'emoji' => '✋',
            'rule' => ['type' => 'accuracy', 'min' => 80, 'count' => 5, 'consecutive' => true],
        ],
        'acc_precision_pro' => [
            'category' => 'acc',
            'name' => 'Precision Pro',
            'description' => 'Score 85% or higher on 10 readings in a row.',
            'emoji' => '🔬',
            'rule' => ['type' => 'accuracy', 'min' => 85, 'count' => 10, 'consecutive' => true],
        ],
        'acc_practice_pays_off' => [
            'category' => 'acc',
            'name' => 'Practice Pays Off',
            'description' => 'Beat your old score on a book by 20 points or more.',
            'emoji' => '🌻',
            'rule' => ['type' => 'pays_off', 'gain' => 20],
        ],
        'acc_flawless_five' => [
            'category' => 'acc',
            'name' => 'Flawless Five',
            'description' => 'Score 95% or higher on 5 readings.',
            'emoji' => '✨',
            'rule' => ['type' => 'accuracy', 'min' => 95, 'count' => 5],
        ],
        'speed_steady_pace' => [
            'category' => 'speed',
            'name' => 'Steady Pace',
            'description' => 'Read 20 words per minute in one reading.',
            'emoji' => '🐢',
            'rule' => ['type' => 'wcpm', 'min' => 20],
        ],
        'speed_getting_faster' => [
            'category' => 'speed',
            'name' => 'Getting Faster',
            'description' => 'Read 30 words per minute in one reading.',
            'emoji' => '🐇',
            'rule' => ['type' => 'wcpm', 'min' => 30],
        ],
        'speed_quick_reader' => [
            'category' => 'speed',
            'name' => 'Quick Reader',
            'description' => 'Read 40 words per minute in one reading.',
            'emoji' => '🚲',
            'rule' => ['type' => 'wcpm', 'min' => 40],
        ],
        'speed_speedy_reader' => [
            'category' => 'speed',
            'name' => 'Speedy Reader',
            'description' => 'Read 50 words per minute in one reading.',
            'emoji' => '🏃',
            'rule' => ['type' => 'wcpm', 'min' => 50],
        ],
        'speed_swift_reader' => [
            'category' => 'speed',
            'name' => 'Swift Reader',
            'description' => 'Read 60 words per minute in one reading.',
            'emoji' => '🦅',
            'rule' => ['type' => 'wcpm', 'min' => 60],
        ],
        'speed_rocket_reader' => [
            'category' => 'speed',
            'name' => 'Rocket Reader',
            'description' => 'Read 70 words per minute in one reading.',
            'emoji' => '🚀',
            'rule' => ['type' => 'wcpm', 'min' => 70],
        ],
        'speed_race_car_reader' => [
            'category' => 'speed',
            'name' => 'Race Car Reader',
            'description' => 'Read 80 words per minute in one reading.',
            'emoji' => '🏎️',
            'rule' => ['type' => 'wcpm', 'min' => 80],
        ],
        'speed_cheetah_reader' => [
            'category' => 'speed',
            'name' => 'Cheetah Reader',
            'description' => 'Read 90 words per minute in one reading.',
            'emoji' => '🐆',
            'rule' => ['type' => 'wcpm', 'min' => 90],
        ],
        'speed_jet_reader' => [
            'category' => 'speed',
            'name' => 'Jet Reader',
            'description' => 'Read 100 words per minute in one reading.',
            'emoji' => '✈️',
            'rule' => ['type' => 'wcpm', 'min' => 100],
        ],
        'speed_comet_reader' => [
            'category' => 'speed',
            'name' => 'Comet Reader',
            'description' => 'Read 110 words per minute in one reading.',
            'emoji' => '☄️',
            'rule' => ['type' => 'wcpm', 'min' => 110],
        ],
        'leveled_up' => [
            'category' => 'level',
            'name' => 'Leveled Up',
            'description' => 'Move up a reading level for the first time.',
            'emoji' => '📈',
            'rule' => ['type' => 'level_ups', 'target' => 1],
        ],
        'level_developing_reader' => [
            'category' => 'level',
            'name' => 'Developing Reader',
            'description' => 'Reach the Developing level.',
            'emoji' => '🌿',
            'rule' => ['type' => 'level_reached', 'level' => 'Developing'],
        ],
        'level_proficient_reader' => [
            'category' => 'level',
            'name' => 'Proficient Reader',
            'description' => 'Reach the Proficient level.',
            'emoji' => '🌟',
            'rule' => ['type' => 'level_reached', 'level' => 'Proficient'],
        ],
        'level_steady_climber' => [
            'category' => 'level',
            'name' => 'Steady Climber',
            'description' => 'Move up a reading level 2 times.',
            'emoji' => '🥾',
            'rule' => ['type' => 'level_ups', 'target' => 2],
        ],
        'level_summit_seeker' => [
            'category' => 'level',
            'name' => 'Summit Seeker',
            'description' => 'Move up a reading level 3 times.',
            'emoji' => '🏔️',
            'rule' => ['type' => 'level_ups', 'target' => 3],
        ],
        'level_comeback_kid' => [
            'category' => 'level',
            'name' => 'Comeback Kid',
            'description' => 'Move back up after dipping down a level.',
            'emoji' => '🔁',
            'rule' => ['type' => 'comeback'],
        ],
        'level_holding_strong' => [
            'category' => 'level',
            'name' => 'Holding Strong',
            'description' => 'Stay at Proficient for 10 readings.',
            'emoji' => '🛡️',
            'rule' => ['type' => 'hold_level', 'level' => 'Proficient', 'target' => 10],
        ],
        'level_graduate' => [
            'category' => 'level',
            'name' => 'Graduate',
            'description' => 'Get promoted to the next grade.',
            'emoji' => '🎓',
            'rule' => ['type' => 'promoted'],
        ],
        'level_skill_climber' => [
            'category' => 'level',
            'name' => 'Skill Climber',
            'description' => 'Reach Halfway There on all your skills.',
            'emoji' => '🧗',
            'rule' => ['type' => 'skills', 'min' => 50],
        ],
        'level_all_skills_star' => [
            'category' => 'level',
            'name' => 'All Skills Star',
            'description' => 'Reach the last star on every skill road.',
            'emoji' => '🌠',
            'rule' => ['type' => 'skills', 'min' => 88],
        ],
        'goal_first_goal' => [
            'category' => 'goal',
            'name' => 'First Goal',
            'description' => 'Hit your weekly reading goal once.',
            'emoji' => '🥅',
            'rule' => ['type' => 'goal_weeks', 'target' => 1],
        ],
        'goal_two_weeks_strong' => [
            'category' => 'goal',
            'name' => 'Two Weeks Strong',
            'description' => 'Hit your weekly goal 2 weeks in a row.',
            'emoji' => '🗓️',
            'rule' => ['type' => 'goal_weeks', 'target' => 2],
        ],
        'goal_goal_getter' => [
            'category' => 'goal',
            'name' => 'Goal Getter',
            'description' => 'Hit your weekly goal 4 weeks in a row.',
            'emoji' => '🌤️',
            'rule' => ['type' => 'goal_weeks', 'target' => 4],
        ],
        'goal_finish_line' => [
            'category' => 'goal',
            'name' => 'Finish Line',
            'description' => 'Hit your weekly goal 8 weeks in a row.',
            'emoji' => '🏁',
            'rule' => ['type' => 'goal_weeks', 'target' => 8],
        ],
        'goal_early_finisher' => [
            'category' => 'goal',
            'name' => 'Early Finisher',
            'description' => 'Hit your weekly goal by Wednesday.',
            'emoji' => '⏱️',
            'rule' => ['type' => 'goal_by_wednesday'],
        ],
        'goal_overachiever' => [
            'category' => 'goal',
            'name' => 'Overachiever',
            'description' => 'Read 10 times in one week.',
            'emoji' => '➕',
            'rule' => ['type' => 'week_count', 'target' => 10],
        ],
        'goal_perfect_week' => [
            'category' => 'goal',
            'name' => 'Perfect Week',
            'description' => 'Read on all 7 days of one week.',
            'emoji' => '✅',
            'rule' => ['type' => 'week_all_days'],
        ],
        'goal_weekend_reader' => [
            'category' => 'goal',
            'name' => 'Weekend Reader',
            'description' => 'Read on both Saturday and Sunday.',
            'emoji' => '🌞',
            'rule' => ['type' => 'weekend_both'],
        ],
        'goal_monthly_milestone' => [
            'category' => 'goal',
            'name' => 'Monthly Milestone',
            'description' => 'Hit your weekly goal 4 times in one month.',
            'emoji' => '🎊',
            'rule' => ['type' => 'goal_in_month', 'times' => 4],
        ],
        'goal_goal_master' => [
            'category' => 'goal',
            'name' => 'Goal Master',
            'description' => 'Hit your weekly goal 12 weeks in a row.',
            'emoji' => '🥇',
            'rule' => ['type' => 'goal_weeks', 'target' => 12],
        ],
        'pts_first_100_points' => [
            'category' => 'pts',
            'name' => 'First 100 Points',
            'description' => 'Earn 100 points.',
            'emoji' => '🥉',
            'rule' => ['type' => 'points', 'target' => 100],
        ],
        'pts_200_points' => [
            'category' => 'pts',
            'name' => '200 Points',
            'description' => 'Earn 200 points.',
            'emoji' => '💰',
            'rule' => ['type' => 'points', 'target' => 200],
        ],
        'pts_500_points' => [
            'category' => 'pts',
            'name' => '500 Points',
            'description' => 'Earn 500 points.',
            'emoji' => '💵',
            'rule' => ['type' => 'points', 'target' => 500],
        ],
        'pts_750_points' => [
            'category' => 'pts',
            'name' => '750 Points',
            'description' => 'Earn 750 points.',
            'emoji' => '🏦',
            'rule' => ['type' => 'points', 'target' => 750],
        ],
        'pts_1_000_points' => [
            'category' => 'pts',
            'name' => '1,000 Points',
            'description' => 'Earn 1,000 points.',
            'emoji' => '🎁',
            'rule' => ['type' => 'points', 'target' => 1000],
        ],
        'pts_1_500_points' => [
            'category' => 'pts',
            'name' => '1,500 Points',
            'description' => 'Earn 1,500 points.',
            'emoji' => '🛍️',
            'rule' => ['type' => 'points', 'target' => 1500],
        ],
        'pts_2_000_points' => [
            'category' => 'pts',
            'name' => '2,000 Points',
            'description' => 'Earn 2,000 points.',
            'emoji' => '🎈',
            'rule' => ['type' => 'points', 'target' => 2000],
        ],
        'pts_3_000_points' => [
            'category' => 'pts',
            'name' => '3,000 Points',
            'description' => 'Earn 3,000 points.',
            'emoji' => '🎠',
            'rule' => ['type' => 'points', 'target' => 3000],
        ],
        'pts_5_000_points' => [
            'category' => 'pts',
            'name' => '5,000 Points',
            'description' => 'Earn 5,000 points.',
            'emoji' => '🏰',
            'rule' => ['type' => 'points', 'target' => 5000],
        ],
        'pts_10_000_points' => [
            'category' => 'pts',
            'name' => '10,000 Points',
            'description' => 'Earn 10,000 points. Out of this world!',
            'emoji' => '🌌',
            'rule' => ['type' => 'points', 'target' => 10000],
        ],
        'shelf_book_collector' => [
            'category' => 'shelf',
            'name' => 'Book Collector',
            'description' => 'Put your first book on your bookshelf.',
            'emoji' => '📌',
            'rule' => ['type' => 'first_book'],
        ],
        'shelf_five_on_the_shelf' => [
            'category' => 'shelf',
            'name' => 'Five on the Shelf',
            'description' => 'Read 5 different books.',
            'emoji' => '🗃️',
            'rule' => ['type' => 'distinct_books', 'target' => 5],
        ],
        'shelf_ten_on_the_shelf' => [
            'category' => 'shelf',
            'name' => 'Ten on the Shelf',
            'description' => 'Read 10 different books.',
            'emoji' => '🔖',
            'rule' => ['type' => 'distinct_books', 'target' => 10],
        ],
        'shelf_re_read_rookie' => [
            'category' => 'shelf',
            'name' => 'Re-read Rookie',
            'description' => 'Read the same book 3 times.',
            'emoji' => '📕',
            'rule' => ['type' => 'same_book', 'target' => 3],
        ],
        'shelf_re_read_hero' => [
            'category' => 'shelf',
            'name' => 'Re-read Hero',
            'description' => 'Read the same book 5 times.',
            'emoji' => '♻️',
            'rule' => ['type' => 'same_book', 'target' => 5],
        ],
        'shelf_practice_champion' => [
            'category' => 'shelf',
            'name' => 'Practice Champion',
            'description' => 'Read the same book 10 times.',
            'emoji' => '🏋️',
            'rule' => ['type' => 'same_book', 'target' => 10],
        ],
        'shelf_personal_best' => [
            'category' => 'shelf',
            'name' => 'Personal Best',
            'description' => 'Beat your own best score on a book.',
            'emoji' => '🏅',
            'rule' => ['type' => 'personal_best'],
        ],
        'shelf_favorite_story' => [
            'category' => 'shelf',
            'name' => 'Favorite Story',
            'description' => 'Read the same book 15 times.',
            'emoji' => '❤️',
            'rule' => ['type' => 'same_book', 'target' => 15],
        ],
        'shelf_cover_to_cover' => [
            'category' => 'shelf',
            'name' => 'Cover to Cover',
            'description' => 'Read 20 different books.',
            'emoji' => '📔',
            'rule' => ['type' => 'distinct_books', 'target' => 20],
        ],
        'shelf_shelf_master' => [
            'category' => 'shelf',
            'name' => 'Shelf Master',
            'description' => 'Read 50 different books.',
            'emoji' => '🗂️',
            'rule' => ['type' => 'distinct_books', 'target' => 50],
        ],
        'game_word_builder_rookie' => [
            'category' => 'game',
            'name' => 'Word Builder Rookie',
            'description' => 'Finish your first Word Builder game.',
            'emoji' => '🔤',
            'rule' => ['type' => 'game_plays', 'game' => 'word-builder', 'target' => 1],
        ],
        'game_word_builder_pro' => [
            'category' => 'game',
            'name' => 'Word Builder Pro',
            'description' => 'Reach Level 3 in Word Builder.',
            'emoji' => '🧱',
            'rule' => ['type' => 'game_level', 'game' => 'word-builder', 'min' => 3],
        ],
        'game_master_builder' => [
            'category' => 'game',
            'name' => 'Master Builder',
            'description' => 'Finish 10 Word Builder games.',
            'emoji' => '🏗️',
            'rule' => ['type' => 'game_plays', 'game' => 'word-builder', 'target' => 10],
        ],
        'game_letter_match_rookie' => [
            'category' => 'game',
            'name' => 'Letter Match Rookie',
            'description' => 'Finish your first Letter Match game.',
            'emoji' => '🃏',
            'rule' => ['type' => 'game_plays', 'game' => 'letter-match', 'target' => 1],
        ],
        'game_memory_master' => [
            'category' => 'game',
            'name' => 'Memory Master',
            'description' => 'Reach Level 3 in Letter Match.',
            'emoji' => '🎴',
            'rule' => ['type' => 'game_level', 'game' => 'letter-match', 'min' => 3],
        ],
        'game_game_on' => [
            'category' => 'game',
            'name' => 'Game On',
            'description' => 'Play 5 practice games.',
            'emoji' => '🎮',
            'rule' => ['type' => 'game_plays', 'target' => 5],
        ],
        'game_game_champion' => [
            'category' => 'game',
            'name' => 'Game Champion',
            'description' => 'Play 25 practice games.',
            'emoji' => '🕹️',
            'rule' => ['type' => 'game_plays', 'target' => 25],
        ],
        'game_lucky_match' => [
            'category' => 'game',
            'name' => 'Lucky Match',
            'description' => 'Clear a Letter Match round with no mistakes.',
            'emoji' => '🎲',
            'rule' => ['type' => 'game_perfect', 'game' => 'letter-match'],
        ],
        'game_alphabet_ace' => [
            'category' => 'game',
            'name' => 'Alphabet Ace',
            'description' => 'Match the whole alphabet in Letter Match.',
            'emoji' => '🔠',
            'rule' => ['type' => 'game_top_cleared', 'game' => 'letter-match'],
        ],
        'game_practice_party' => [
            'category' => 'game',
            'name' => 'Practice Party',
            'description' => 'Play both games on the same day.',
            'emoji' => '🥳',
            'rule' => ['type' => 'game_both_same_day'],
        ],
        'special_reading_check_done' => [
            'category' => 'special',
            'name' => 'Reading Check Done',
            'description' => 'Finish your first reading check.',
            'emoji' => '🗺️',
            'rule' => ['type' => 'diagnostic_done'],
        ],
        'special_early_bird' => [
            'category' => 'special',
            'name' => 'Early Bird',
            'description' => 'Finish a reading before 8 in the morning.',
            'emoji' => '🌅',
            'rule' => ['type' => 'hour', 'before' => 8],
        ],
        'special_night_owl' => [
            'category' => 'special',
            'name' => 'Night Owl',
            'description' => 'Finish a reading after 7 at night.',
            'emoji' => '🦉',
            'rule' => ['type' => 'hour', 'after' => 19],
        ],
        'special_story_detective' => [
            'category' => 'special',
            'name' => 'Story Detective',
            'description' => 'Answer every question right on a story quiz.',
            'emoji' => '🔍',
            'rule' => ['type' => 'quiz_perfect', 'target' => 1],
        ],
        'special_super_detective' => [
            'category' => 'special',
            'name' => 'Super Detective',
            'description' => 'Answer every question right on 5 story quizzes.',
            'emoji' => '🕵️',
            'rule' => ['type' => 'quiz_perfect', 'target' => 5],
        ],
        'special_extra_practice_explorer' => [
            'category' => 'special',
            'name' => 'Extra Practice Explorer',
            'description' => 'Read an Extra Practice story from the Repository.',
            'emoji' => '🧭',
            'rule' => ['type' => 'extra_practice'],
        ],
        'special_teamwork' => [
            'category' => 'special',
            'name' => 'Teamwork',
            'description' => 'Read a story from your Teacher and one from home in the same week.',
            'emoji' => '🤝',
            'rule' => ['type' => 'teamwork'],
        ],
        'special_taras_friend' => [
            'category' => 'special',
            'name' => 'Tara\'s Friend',
            'description' => 'Come back to TaraBasa on 30 different days.',
            'emoji' => '🧸',
            'rule' => ['type' => 'days_read', 'target' => 30],
        ],
        'special_welcome_back' => [
            'category' => 'special',
            'name' => 'Welcome Back',
            'description' => 'Come back to read after a week away.',
            'emoji' => '🔙',
            'rule' => ['type' => 'welcome_back'],
        ],
        'special_super_reader' => [
            'category' => 'special',
            'name' => 'Super Reader',
            'description' => 'Earn 50 badges.',
            'emoji' => '🎉',
            'rule' => ['type' => 'badge_count', 'target' => 50],
        ],
    ],
]; 
