<?php

/**
 * The first-login reading check.
 *
 * It is about where the CHILD is, not which grade they are enrolled in. The
 * Parent's own description of the child's reading picks where the check starts
 * on a ladder that runs from naming letters up to reading a full passage, and
 * the ladder is the same for every child: a Grade 3 child who cannot read yet
 * starts on letters, a Grade 2 child who reads well starts on a passage.
 * Every rung is real curriculum content: the letters rung is the MATATAG
 * Grade 1 letter competency and every other rung is generated by the
 * generator, which aligns it to the MATATAG guide for the grade it is asked
 * for (the grade in a rung is the grade of the CONTENT, never the child's).
 *
 * The rungs, lowest to highest (each has its own tier of the generator):
 *   0 letters          say the names of six letters
 *   1-3 phonics        Grade 1 phonics reading: simple words, then short
 *                      sentences, then longer ones
 *   4-6 passage        Grade 2 passage reading (about 30, 60 and 100 words)
 *
 * The rungs are grouped by what the recommender's own bands call them
 * (0-2 easy, 3-4 medium, 5-6 hard), and that is also how a landing rung turns
 * into the app's three levels.
 */
return [

    'ladder' => [
        'letters' => [
            'kind' => 'letters',
            // The curriculum guide's own Grade 1 letter competency:
            // RL1PWS-II-1, "Produce the sounds represented by letters" (Phonics
            // and Word Study). It is the only letter competency the guide has,
            // so it is used for every child who needs letters, at any grade.
            'grade' => 1,
            'competency_code' => 'RL1PWS-II-1',
            'mastery' => 'Beginning',
            'band' => [0, 19],
        ],
        'phonics_easy' => [
            'kind' => 'generated', 'grade' => 1, 'competency' => 'foundational_reading', 'activity_type' => 'phonics_reading', 'tier' => 'easy',
            'mastery' => 'Beginning', 'band' => [20, 39],
        ],
        'phonics_medium' => [
            'kind' => 'generated', 'grade' => 1, 'competency' => 'foundational_reading', 'activity_type' => 'phonics_reading', 'tier' => 'medium',
            'mastery' => 'Beginning', 'band' => [40, 59],
        ],
        'phonics_hard' => [
            'kind' => 'generated', 'grade' => 1, 'competency' => 'foundational_reading', 'activity_type' => 'phonics_reading', 'tier' => 'hard',
            'mastery' => 'Developing', 'band' => [60, 71],
        ],
        'passage_easy' => [
            'kind' => 'generated', 'grade' => 2, 'competency' => 'reading_fluency', 'activity_type' => 'passage_reading', 'tier' => 'easy',
            'mastery' => 'Developing', 'band' => [72, 84],
        ],
        'passage_medium' => [
            'kind' => 'generated', 'grade' => 2, 'competency' => 'reading_fluency', 'activity_type' => 'passage_reading', 'tier' => 'medium',
            'mastery' => 'Proficient', 'band' => [85, 92],
        ],
        'passage_hard' => [
            'kind' => 'generated', 'grade' => 2, 'competency' => 'reading_fluency', 'activity_type' => 'passage_reading', 'tier' => 'hard',
            'mastery' => 'Proficient', 'band' => [93, 100],
        ],
    ],

    'letters' => [
        // Six letters per item, in the usual phonics teaching order (s a t p i n
        // first). Two sets, so a child who swings back to this rung is not asked
        // the same letters twice. Letters the speech model reliably confuses
        // (Y heard as "why", Z as "c", X, Q) are left out on purpose.
        'sets' => [
            ['label' => 'A', 'letters' => ['S', 'A', 'T', 'P', 'I', 'N']],
            ['label' => 'B', 'letters' => ['M', 'D', 'O', 'G', 'C', 'B']],
        ],
    ],

    // Where the check starts for each thing a Parent can say about the child's
    // reading, as a position on the ladder above. "Not sure" gives no signal. A
    // child whose Parent says they "know letters and sounds" starts on the
    // first phonics rung; if that goes badly the check steps down to letters by
    // itself.
    'stage_start' => [
        'starting' => 0,
        'letters' => 1,
        'blending' => 1,
        'sentences' => 3,
        'independent' => 5,
    ],

    // Children added before the Parent's answers were stored have only the
    // level that was computed from them.
    'legacy_mastery_start' => [
        'Beginning' => 1,
        'Developing' => 3,
        'Proficient' => 4,
    ],

    // What a check that was already running when the ladder replaced the old
    // three tiers (easy/medium/hard) still needs to finish.
    'legacy_tiers' => [
        'easy' => ['mastery' => 'Beginning', 'band' => [0, 59]],
        'medium' => ['mastery' => 'Developing', 'band' => [60, 84]],
        'hard' => ['mastery' => 'Proficient', 'band' => [85, 100]],
    ],

    // How many rungs either side of the starting rung a check of at most three
    // items can reach (one step per item after the first), so only the content
    // that can actually be needed is generated.
    'reach' => 2,
];
